### ISSUE TITLE
issues after installing Dashbord and demo_dashbord

### ISSUE THREAD

**Issue by diassynthesis** [trobz/openerp-dashboard#1]
Dear Sir;
I know that the work is still  in progress and the modules are not usable.
I just want to point out some errors I encountered after installation and uninstallation of the dashboard module (just for test).
1. After the installation: i can't access any " Calandar Views" (see attached files for errors under firefox and Chrome) and i can't access any other menu (only after doing a refresh with F5 key).
    If i uninstall the dashboard module all "Calandar Views" are working.
2. But after uninstall process, i encouter a second issue when accessing "Human resources"
     The cause is that when uninstalling the dashbord module the column "write_date' is deleted from the table "hr_employee".
Hope this can help, and thank you for the work you are doing.

Best regards.

PS: Sorry for my English.

![dashboard trobz issue chrome](https://f.cloud.github.com/assets/3822648/2057918/fd3bc21c-8b54-11e3-9b56-3cb94c869fe3.png)
![dashboard trobz issue-firefox](https://f.cloud.github.com/assets/3822648/2057921/07561c34-8b55-11e3-8f46-bb7d05bf84fd.png)
![after uninstall](https://f.cloud.github.com/assets/3822648/2057922/10f19444-8b55-11e3-8ab3-b058fc468200.png)

**Comment by zazabe** [comment]
Hi,

Yes, we are currently working on this module to provide a simplified (but less powerful) version, without SQL definition, and the advanced version in another module.

Thanks for testing it early stage and reporting bugs :)

I did some investigation about your bug report:
- about the `hr_employee` bug, it's because in `demo_dashboard`, the `write_date` is explicitly declared to have a `ir.model.fields` reference to it.  
  It's seems that explicitly declare a special column in a module will remove it when this module is uninstalled... [see my question here](http://help.openerp.com/question/43114/why-special-columns-are-not-handled-as-other-fields/)  
  solution: change the `demo_dashboard` module and make it independent from any extra module...
- seems we have issues with "OpenERP apps" view, because all core js files are reloaded from apps.openerp.com when we go on this screen... so all our core overrides are overrided again... I [opened a question on this point](http://help.openerp.com/question/43112/is-there-any-reasons-to-load-all-openerp-js-files-from-appsopenerpcom-on-apps-list-view/), but anyhow, we will have to found a workaround...  

About JS errors, could you try to reproduce them in debug mode and give me the console output with the full error stack ?

Thanks for your interest in this module, I will keep you informed if we solve any of these issues. 

Michel

**Comment by diassynthesis** [comment]
Hello;
Thank you for your response, 
About the JS errors, i will test and keep you informed.
For the write_date (in the demo_dashboard/hr_employee.py file): i think we must put a constraint on it (like ON DELETE NO ACTION and also ON UPDATE .....).

Best regards.

**Comment by diassynthesis** [comment]
hello;

1- I've re-installed "dashboard" and it seems working well (no error on Calendar Views).... But there is no submenu "Dashboard"  as defined in dashboard_view.xml at line 8. ( I suppose because there is no submenu under it nor an Action_view)

The question is: Why it's working now with no errors?

2- When i try to install "demo_dashboard", the state of the module turns to "to  install" (Blue state) with the following message error under Chrome (and no error messge under firefox) :
![demo_dashboard-install error chrome](https://f.cloud.github.com/assets/3822648/2242067/8efaa4d4-9cf3-11e3-82b6-0bc38874bbaa.png)

Here after a part from my openerp-server.log: 
---log content---

2014-02-24 01:25:01,878 9400 INFO DevDB openerp.modules.loading: loading 590 modules...
2014-02-24 01:25:01,906 9400 INFO DevDB openerp.modules.module: module demo_dashboard: creating or updating database tables
2014-02-24 01:25:02,183 9400 INFO DevDB openerp.modules.loading: module demo_dashboard: loading data/dashboard.xml
2014-02-24 01:25:02,193 9400 INFO DevDB openerp.modules.loading: module demo_dashboard: loading data/widget_number.xml
2014-02-24 01:25:02,249 9400 INFO DevDB openerp.modules.loading: module demo_dashboard: loading data/widget_list.xml
2014-02-24 01:25:02,344 9400 INFO DevDB openerp.modules.loading: module demo_dashboard: loading data/widget_graph.xml
2014-02-24 01:25:02,357 9400 ERROR DevDB openerp.sql_db: bad query: insert into "dashboard_widget" (id,"type","limit","name","method",create_uid,create_date,write_uid,write_date) values (16,'graph','80','Total Sales (Pie)','execute',1,(now() at time zone 'UTC'),1,(now() at time zone 'UTC'))
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "identifier" violates not-null constraint

2014-02-24 01:25:02,358 9400 ERROR DevDB openerp.tools.convert: Parse error in /usr/lib/pymodules/python2.7/openerp/addons/demo_dashboard/data/widget_graph.xml:27: 
<record id="graph_widget_3" model="dashboard.widget">
            <field name="name">Total Sales (Pie)</field>
            <field name="method">execute</field>
            <field name="type">graph</field>
            <field name="limit">80</field>
        </record>
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 847, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 814, in _tag_record
    id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_model.py", line 967, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/usr/lib/pymodules/python2.7/openerp/addons/connector/producer.py", line 42, in create
    record_id = create_original(self, cr, uid, vals, context=context)
  File "/usr/lib/pymodules/python2.7/openerp/osv/orm.py", line 4457, in create
    cr.execute('insert into "'+self._table+'" (id'+upd0+") values ("+str(id_new)+upd1+')', tuple(upd2))
  File "/usr/lib/pymodules/python2.7/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "identifier" violates not-null constraint

2014-02-24 01:25:02,393 9400 INFO DevDB openerp.modules.loading: loading 1 modules...
2014-02-24 01:25:02,461 9400 WARNING DevDB openerp.modules.module: module anytracker: module not found
2014-02-24 01:25:02,461 9400 WARNING DevDB openerp.modules.module: module anytracker: module not found
2014-02-24 01:25:02,461 9400 WARNING DevDB openerp.modules.module: module anytracker: module not found
2014-02-24 01:25:02,461 9400 WARNING DevDB openerp.modules.graph: module anytracker: not installable, skipped
2014-02-24 01:25:02,610 9400 WARNING DevDB openerp.modules.graph: module web_process_prettyprint: not installable, skipped
2014-02-24 01:25:02,888 9400 WARNING DevDB openerp.modules.graph: Some modules were not loaded.
2014-02-24 01:25:02,891 9400 INFO DevDB openerp.modules.loading: loading 589 modules...
2014-02-24 01:25:03,079 9400 INFO DevDB openerp.osv.orm: Missing many2one field definition for _inherits reference "cost_id" in "fleet.vehicle.log.fuel", using default one.
2014-02-24 01:25:03,079 9400 INFO DevDB openerp.osv.orm: Missing many2one field definition for _inherits reference "cost_id" in "fleet.vehicle.log.services", using default one.
2014-02-24 01:25:03,081 9400 INFO DevDB openerp.osv.orm: Missing many2one field definition for _inherits reference "cost_id" in "fleet.vehicle.log.contract", using default one.
2014-02-24 01:25:03,549 9404 INFO DevDB openerp.osv.orm: Missing many2one field definition for _inherits reference "attachment_id" in "shipping.label", using default one.
2014-02-24 01:25:04,496 9404 INFO DevDB openerp.modules.loading: Modules loaded.
2014-02-24 01:25:04,958 9404 WARNING DevDB openerp.loglevels: The netsvc.Logger API shouldn't be used anymore, please use the standard `logging.getLogger` API instead.
2014-02-24 01:25:04,959 9404 WARNING DevDB openerp.loglevels: notifyChannel API shouldn't be used anymore, please use the standard `logging` module instead.
2014-02-24 01:25:04,959 9404 INFO DevDB openerp.loglevels.deprecated.report_aeroo: OpenOffice.org connection successfully established
2014-02-24 01:25:04,971 9404 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.sample_report (res.partner)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:04,978 9404 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.hr_payroll_register_report (hr.payroll.register)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:04,983 9404 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.hr_daily_manpower (hr.department)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:04,988 9404 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.hr_payroll_net (hr.payroll.register)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:04,996 9404 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.account_general_ledger_odt (account.account)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:05,001 9404 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.account_general_ledger_ods (account.account)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:05,006 9404 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.printscreen.list (ir.ui.view)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:06,417 9400 INFO DevDB openerp.osv.orm: Missing many2one field definition for _inherits reference "attachment_id" in "shipping.label", using default one.
2014-02-24 01:25:07,263 9400 INFO DevDB openerp.modules.loading: Modules loaded.
2014-02-24 01:25:07,451 9400 WARNING DevDB openerp.loglevels: The netsvc.Logger API shouldn't be used anymore, please use the standard `logging.getLogger` API instead.
2014-02-24 01:25:07,452 9400 WARNING DevDB openerp.loglevels: notifyChannel API shouldn't be used anymore, please use the standard `logging` module instead.
2014-02-24 01:25:07,452 9400 INFO DevDB openerp.loglevels.deprecated.report_aeroo: OpenOffice.org connection successfully established
2014-02-24 01:25:07,457 9400 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.sample_report (res.partner)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:07,464 9400 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.hr_payroll_register_report (hr.payroll.register)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:07,468 9400 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.hr_daily_manpower (hr.department)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:07,472 9400 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.hr_payroll_net (hr.payroll.register)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:07,476 9400 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.account_general_ledger_odt (account.account)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:07,479 9400 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.account_general_ledger_ods (account.account)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:07,484 9400 INFO DevDB openerp.addons.report_aeroo.report_aeroo: registering report.printscreen.list (ir.ui.view)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 200, in get
    return cls.registries[db_name]
KeyError: 'DevDB'
2014-02-24 01:25:07,497 9400 ERROR DevDB openerp.netsvc: Erreur d'intÃ©gritÃ©
L'opÃ©ration n'a pas pu Ãªtre terminÃ©e, probablement Ã  la suite d'une :
- suppression : vous avez essayer de supprimer un enregistrement auquel d'autres enregistrements font rÃ©fÃ©rence
- crÃ©ation/modification : un champ requis n'a pas Ã©tÃ© correctement rempli

[objet ayant pour rÃ©fÃ©rence : identifier - identifier]
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/pymodules/python2.7/openerp/addons/hotdebug/hook.py", line 124, in wrapped
    return fn(_args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/hotdebug/hook.py", line 67, in wrapped
    return fn(_args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/usr/lib/pymodules/python2.7/openerp/addons/anybus_trigger_user/trigger.py", line 82, in execute
    res = openerp_execute(self, db, uid, obj, method, _args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 174, in wrapper
    netsvc.abort_response(1, _('Integrity Error'), 'warning', msg)
  File "/usr/lib/pymodules/python2.7/openerp/netsvc.py", line 71, in abort_response
    raise openerp.osv.osv.except_osv(description, details)
except_osv: (u"Erreur d'int\xe9grit\xe9", u"L'op\xe9ration n'a pas pu \xeatre termin\xe9e, probablement \xe0 la suite d'une :\n- suppression : vous avez essayer de supprimer un enregistrement auquel d'autres enregistrements font r\xe9f\xe9rence\n- cr\xe9ation/modification : un champ requis n'a pas \xe9t\xe9 correctement rempli\n\n[objet ayant pour r\xe9f\xe9rence : identifier - identifier]")
2014-02-24 01:25:07,501 9400 DEBUG DevDB openerp.addons.web.http: <--
{'error': {'code': 200,
           'data': {'debug': 'Client Traceback (most recent call last):\n  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 204, in dispatch\n    response["result"] = method(self, *_self.params)\n  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1132, in call_button\n    action = self._call_kw(req, model, method, args, {})\n  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1120, in _call_kw\n    return getattr(req.session.model(model), method)(_args, **kwargs)\n  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 42, in proxy\n    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)\n  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 30, in proxy_method\n    result = self.session.send(self.service_name, method, *args)\n  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 91, in send\n    raise xmlrpclib.Fault(code_string % (e.name, e.value), \'\')\n\n\nServer ',
                    'fault_code': u"warning -- Erreur d'int\xe9grit\xe9\n\nL'op\xe9ration n'a pas pu \xeatre termin\xe9e, probablement \xe0 la suite d'une :\n- suppression : vous avez essayer de supprimer un enregistrement auquel d'autres enregistrements font r\xe9f\xe9rence\n- cr\xe9ation/modification : un champ requis n'a pas \xe9t\xe9 correctement rempli\n\n[objet ayant pour r\xe9f\xe9rence : identifier - identifier]",
                    'type': 'server_exception'},
           'message': 'OpenERP Server Error'},
 'id': 'r847',
 'jsonrpc': '2.0'}

-----END-----
Best regards.

**Comment by zazabe** [comment]
@sbevnc can you check this?
